version: '3.8'

services:
  moneyplanet-be:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: moneyplanet-spring-server:latest
    restart: always
    container_name: moneyplanet-spring-server
    depends_on:
      - moneyplanet-db
      - moneyplanet-redis
    ports:
      - "8080:8080"
    networks:
      - app-network

  moneyplanet-db:
    image: mysql:8.0.33
    container_name: moneyplanet-spring-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  moneyplanet-redis:
    image: redis:7.2
    container_name: moneyplanet-spring-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  mysql_data:
  redis_data: